### ISSUE TITLE
Search bar for Charmed Kubeflow docs?

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmed-kubeflow.io#134]
Would it be possible to get a search bar at the top of https://charmed-kubeflow.io/docs , as we already have for e.g., https://juju.is/docs/olm ?

**Comment by carkod** [comment]
> Hey we are currently having a spike around improving our docs and this is one of the features we would like to achieve before Christmas break, would it be possible to achieve this in that timeline?

Yes, @petesfrench is already working on it.

**Comment by carkod** [comment]
Closing, this is live https://charmed-kubeflow.io/docs
