### ISSUE TITLE
Collapsible navigation levels for Charmed Kubeflow docs

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmed-kubeflow.io#135]
@andreeamun likes the collapsible side bar on this page https://juju.is/docs/olm and would like the same for this page: https://charmed-kubeflow.io/docs . Would that be possible? When? Thanks in advance!

@bartaz pinging you because you recently helped with https://github.com/canonical/charmhub.io/issues/1418 and this is similar.

---
Originally filed https://github.com/canonical/charmhub.io/issues/1421 , refiling here at @Lukewh 's request.

**Comment by tmihoc** [comment]
@petesfrench Has this already been implemented? I've refreshed https://charmed-kubeflow.io/docs but I don't see it. Or is the change not live yet?

**Comment by petesfrench** [comment]
Hi @tmihoc, we are just in the process of deploying it. You should be able to see the changes live shortly
