### ISSUE TITLE
Need better default column widths

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmed-kubeflow.io#137]
The default column table width is suboptimal. See the example below from [this doc](https://charmed-kubeflow.io/docs/operators-and-bundles). Would it be possible to get better defaults? PS I know this was done successfully for Juju Docs. 

![image](https://user-images.githubusercontent.com/38667005/203944669-58964a3f-5f72-4ea9-963b-1b645faeb0b7.png)

**Comment by sowasred2012** [comment]
@lyubomir-popov knows of a Vanilla utility class/setting we could use.

**Comment by lyubomir-popov** [comment]
Hi @tmihoc, the vanilla default for tables is `table-layout: fixed`; It requires column widths specified on the `th` cells, or it distributes space evenly.

You can change that on site level with a vanilla setting, or on an individual table with a class. For documentation sites that pull content from discourse, the site level one makes more sense. Details on how to do it are documented [here](https://vanillaframework.io/docs/settings/table-layout)

**Comment by tmihoc** [comment]
Thanks, @lyubomir-popov . @sowasred2012 Correct me if I'm wrong, but I think I don't have the authority to make such changes myself. Could someone in the web team help? Thanks in advance!

**Comment by sowasred2012** [comment]
@tmihoc yep, we'll take this one and let you know when it's updated :+1:

**Comment by DomFleischmann** [comment]
Hey we are currently having a spike around improving our docs and this is one of the features we would like to achieve before Christmas break, would it be possible to achieve this in that timeline?

**Comment by evilnick** [comment]
see also https://github.com/canonical/anbox-cloud.io/issues/273

**Comment by sowasred2012** [comment]
@tmihoc this is live now - and there's a fix for anbox-cloud.io landing very soon.

**Comment by tmihoc** [comment]
Thanks a lot, @sowasred2012 !
