### ISSUE TITLE
Redirect from https://charmed-kubeflow.io/tutorials to https://charmed-kubeflow.io/docs

### ISSUE THREAD

**Issue by tmihoc** [canonical/charmed-kubeflow.io#143]
Hi! We need a redirect from https://charmed-kubeflow.io/tutorials (now unpublished) to https://charmed-kubeflow.io/docs. How do we go about getting that? Thanks!

 (pinging @sowasred2012 because he's helped us with the unpublishing step before and also @andreeamun as a stakeholder).

**Comment by petesfrench** [comment]
Closing as this was addressed in [this pr](https://github.com/canonical/charmed-kubeflow.io/pull/145)
