### ISSUE TITLE
The resource from “https://charmed-kubeflow.io/static/css/styles.css?v=df9b1c4” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff)

### ISSUE THREAD

**Issue by nobuto-m** [canonical/charmed-kubeflow.io#153]
The quickstart page comes up **without** CSS applied.
https://charmed-kubeflow.io/docs/quickstart

![image](https://user-images.githubusercontent.com/4356209/217240301-b4f8994b-6203-4132-8f62-b71e7a795643.png)

Both Firefox and Chrome are giving similar errors:

[Firefox]
```
The resource from “https://charmed-kubeflow.io/static/css/styles.css?v=df9b1c4” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

[Chrome]
```
Refused to apply style from 'https://charmed-kubeflow.io/static/css/styles.css?v=df9b1c4' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
Refused to apply style from 'https://charmed-kubeflow.io/static/css/styles.css?v=df9b1c4' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

**Comment by CalvinHartwell** [comment]
I am able to replicate this 100% repeatedly using FF in Private Browsing mode. The CSS stylesheet (https://charmed-kubeflow.io/static/css/styles.css?v=df9b1c4) and similar JS files appear to return 404s which causes the error. It appears that some data is missing from the request or cookies need to be accepted first before this page starts to function correctly.

**Comment by anthonydillon** [comment]
A release of the site has resolved this issue. Please let me know if you see it again.
